// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9b9ATDNzgrvcJbQNFOC6G93LwkftDSGo',
    appId: '1:707747030679:web:5f7c4ab0bee21ef2db6bd2',
    messagingSenderId: '707747030679',
    projectId: 'digouter',
    authDomain: 'digouter.firebaseapp.com',
    databaseURL: 'https://digouter-default-rtdb.firebaseio.com',
    storageBucket: 'digouter.appspot.com',
    measurementId: 'G-K774Z13XD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPSgcC3R1hHLSOgoo-AjIAu12th4ZTvTA',
    appId: '1:707747030679:android:dbcedb3cde5acca2db6bd2',
    messagingSenderId: '707747030679',
    projectId: 'digouter',
    databaseURL: 'https://digouter-default-rtdb.firebaseio.com',
    storageBucket: 'digouter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvgjJWKyvkzKFW3Y0C4kpDSvMvk6FmN4',
    appId: '1:707747030679:ios:95a9c1a90235afa8db6bd2',
    messagingSenderId: '707747030679',
    projectId: 'digouter',
    databaseURL: 'https://digouter-default-rtdb.firebaseio.com',
    storageBucket: 'digouter.appspot.com',
    iosClientId: '707747030679-uvpoenpkiqvnu517k6c882a1pn87fqbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.digouter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvgjJWKyvkzKFW3Y0C4kpDSvMvk6FmN4',
    appId: '1:707747030679:ios:95a9c1a90235afa8db6bd2',
    messagingSenderId: '707747030679',
    projectId: 'digouter',
    databaseURL: 'https://digouter-default-rtdb.firebaseio.com',
    storageBucket: 'digouter.appspot.com',
    iosClientId: '707747030679-uvpoenpkiqvnu517k6c882a1pn87fqbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.digouter',
  );
}
